//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Settings/GGJ2023InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GGJ2023InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GGJ2023InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GGJ2023InputActions"",
    ""maps"": [
        {
            ""name"": ""General"",
            ""id"": ""68e12916-4e11-4d30-baa6-a3473f4389eb"",
            ""actions"": [
                {
                    ""name"": ""Player1_Horizontal Axis"",
                    ""type"": ""Value"",
                    ""id"": ""14b20b32-247a-45c8-a7a8-b79b78c47b66"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Player1_Vertical Axis"",
                    ""type"": ""Button"",
                    ""id"": ""fa3beeff-0479-42ac-885d-58d2508301c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Player2_Horizontal Axis"",
                    ""type"": ""Value"",
                    ""id"": ""992983ed-0733-4060-b2d2-e76a4df412ea"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Player2_Vertical Axis"",
                    ""type"": ""Button"",
                    ""id"": ""6d5da0bd-31cb-4880-ba2c-e0ff7fcff877"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""1daf6b88-7b65-46cf-9f84-cb4fd08baf48"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player1_Horizontal Axis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8117853b-6b33-46e6-8333-e6b07ad1274d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player1_Horizontal Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2d998a39-aea6-413e-bc9d-3f03ea2ef1b0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player1_Horizontal Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""4fcd2231-f138-4759-8a01-bd23cd089847"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player1_Vertical Axis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""be4fbf25-d0fc-473f-9339-731ec53d567e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player1_Vertical Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""18c9fcc5-6bb8-4d8f-8c9b-672384071a31"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player1_Vertical Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""150ab414-a46c-4c58-83b1-b59bfdaf03ac"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player2_Vertical Axis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""ba7edd08-9c99-4407-b5b9-d874e11d7223"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player2_Vertical Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2283988f-5ccf-4396-925b-33739352e8df"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player2_Vertical Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""d294c07a-cb50-483a-8f3b-de129f4b273d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player2_Horizontal Axis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9352ad87-9f8c-4ed9-a7fe-a3d46b35446c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player2_Horizontal Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""90fd0b3d-3119-44b2-bec5-bf3955504db5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Player2_Horizontal Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_Player1_HorizontalAxis = m_General.FindAction("Player1_Horizontal Axis", throwIfNotFound: true);
        m_General_Player1_VerticalAxis = m_General.FindAction("Player1_Vertical Axis", throwIfNotFound: true);
        m_General_Player2_HorizontalAxis = m_General.FindAction("Player2_Horizontal Axis", throwIfNotFound: true);
        m_General_Player2_VerticalAxis = m_General.FindAction("Player2_Vertical Axis", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // General
    private readonly InputActionMap m_General;
    private IGeneralActions m_GeneralActionsCallbackInterface;
    private readonly InputAction m_General_Player1_HorizontalAxis;
    private readonly InputAction m_General_Player1_VerticalAxis;
    private readonly InputAction m_General_Player2_HorizontalAxis;
    private readonly InputAction m_General_Player2_VerticalAxis;
    public struct GeneralActions
    {
        private @GGJ2023InputActions m_Wrapper;
        public GeneralActions(@GGJ2023InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Player1_HorizontalAxis => m_Wrapper.m_General_Player1_HorizontalAxis;
        public InputAction @Player1_VerticalAxis => m_Wrapper.m_General_Player1_VerticalAxis;
        public InputAction @Player2_HorizontalAxis => m_Wrapper.m_General_Player2_HorizontalAxis;
        public InputAction @Player2_VerticalAxis => m_Wrapper.m_General_Player2_VerticalAxis;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void SetCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterface != null)
            {
                @Player1_HorizontalAxis.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer1_HorizontalAxis;
                @Player1_HorizontalAxis.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer1_HorizontalAxis;
                @Player1_HorizontalAxis.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer1_HorizontalAxis;
                @Player1_VerticalAxis.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer1_VerticalAxis;
                @Player1_VerticalAxis.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer1_VerticalAxis;
                @Player1_VerticalAxis.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer1_VerticalAxis;
                @Player2_HorizontalAxis.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer2_HorizontalAxis;
                @Player2_HorizontalAxis.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer2_HorizontalAxis;
                @Player2_HorizontalAxis.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer2_HorizontalAxis;
                @Player2_VerticalAxis.started -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer2_VerticalAxis;
                @Player2_VerticalAxis.performed -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer2_VerticalAxis;
                @Player2_VerticalAxis.canceled -= m_Wrapper.m_GeneralActionsCallbackInterface.OnPlayer2_VerticalAxis;
            }
            m_Wrapper.m_GeneralActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Player1_HorizontalAxis.started += instance.OnPlayer1_HorizontalAxis;
                @Player1_HorizontalAxis.performed += instance.OnPlayer1_HorizontalAxis;
                @Player1_HorizontalAxis.canceled += instance.OnPlayer1_HorizontalAxis;
                @Player1_VerticalAxis.started += instance.OnPlayer1_VerticalAxis;
                @Player1_VerticalAxis.performed += instance.OnPlayer1_VerticalAxis;
                @Player1_VerticalAxis.canceled += instance.OnPlayer1_VerticalAxis;
                @Player2_HorizontalAxis.started += instance.OnPlayer2_HorizontalAxis;
                @Player2_HorizontalAxis.performed += instance.OnPlayer2_HorizontalAxis;
                @Player2_HorizontalAxis.canceled += instance.OnPlayer2_HorizontalAxis;
                @Player2_VerticalAxis.started += instance.OnPlayer2_VerticalAxis;
                @Player2_VerticalAxis.performed += instance.OnPlayer2_VerticalAxis;
                @Player2_VerticalAxis.canceled += instance.OnPlayer2_VerticalAxis;
            }
        }
    }
    public GeneralActions @General => new GeneralActions(this);
    public interface IGeneralActions
    {
        void OnPlayer1_HorizontalAxis(InputAction.CallbackContext context);
        void OnPlayer1_VerticalAxis(InputAction.CallbackContext context);
        void OnPlayer2_HorizontalAxis(InputAction.CallbackContext context);
        void OnPlayer2_VerticalAxis(InputAction.CallbackContext context);
    }
}
